########################
##### EXPERIMENTAL #####
########################

#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHOME PRE-BUILT - Wall_Display variation by https://github.com/MichaelHeimann           #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################
substitutions:
  heater_relay: "1" # possible values: 1/2
  temp_units: "째C" #Temperatures in Fahrenheit
  temp_min: "16" #Min supported temperature is 40째F
  temp_max: "26" #Max supported temperature is 80째F
  temp_step: "0.5" #Temperature granularity is 1째F

packages:
  climate_heat: !include ../esphome/nspanel_esphome_addon_climate_heat.yaml
  prebuilt_package: !include nspanel_esphome_prebuilt.yaml

dashboard_import:
  package_import_url: github://Blackymas/NSPanel_HA_Blueprint/prebuilt/Wall_Display.yaml@main
  import_full_config: false

esphome:
  project:
    name: esphome.Wall_Display
  on_boot:
    - priority: 602.0
      then:
        - text.set:
            id: fw_url
            value: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/prebuilt/wall_display.bin"
esp32:
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST: "y"
      CONFIG_BT_BLE_DYNAMIC_ENV_MEMORY: "y"
      CONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC: "y"
      CONFIG_MBEDTLS_SSL_VARIABLE_BUFFER_LENGTH: "y"
      CONFIG_MBEDTLS_DYNAMIC_BUFFER: "y"
      CONFIG_MBEDTLS_DYNAMIC_FREE_CONFIG_DATA: "y"
      CONFIG_MBEDTLS_DYNAMIC_FREE_CA_CERT: "y"
      CONFIG_SPIRAM_TRY_ALLOCATE_WIFI_LWIP: "y"
...
