substitutions:
  device_name: nspanel
  wifi_ssid: "nspanel"
  wifi_password: "NSPanel_HA_Blueprint"
  nextion_update_url: "https://github.com/Blackymas/NSPanel_HA_Blueprint"

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: dev
    files:
      - nspanel_esphome.yaml # Core package only
    refresh: 300s

esphome:
  name_add_mac_suffix: true
  project:
    name: esphome.NSPanel_HA_Blueprint
    version: "4.1dev3"

dashboard_import:
  package_import_url: github://Blackymas/NSPanel_HA_Blueprint/nspanel_esphome_prebuilt.yaml@dev # Must be updated
  import_full_config: false

button:
  - id: !extend tft_update
    internal: true

  - id: !extend tft_reparse_off
    internal: true

wifi:
  ap: {}

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device.
captive_portal:

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none

# Sets up the improv via serial client for Wi-Fi provisioning
improv_serial:
