---
packages:
  core_package: !include advanced/esphome/nspanel_esphome_core.yaml
  #advanced_package: !include advanced/esphome/nspanel_esphome_advanced.yaml
  upload_tft_package: !include advanced/esphome/nspanel_esphome_addon_upload_tft.yaml
...
