####################################################################################################
##### NSPanel ESPHome Add-on for Climate control - Heat                                        #####
##### Add-on for https://github.com/Blackymas/NSPanel_HA_Blueprint                             #####
####################################################################################################

substitutions:
  ### Local thermostat defaults ###
  # https://esphome.io/components/climate/thermostat.html
  heater_relay: "0" # Select 1 for "Relay 1", 2 for "Relay 2" or "0" to a dummy switch/disabled
  # https://esphome.io/components/climate/index.html#base-climate-configuration
  temp_min: "5"
  temp_max: "25"

  ##### DO NOT CHANGE THIS #####
  addon_climate_cool: "false"
  addon_climate_heat: "true"
  ##############################

climate:
  - platform: thermostat
    name: ${device_name} Thermostat
    id: thermostat_embedded
    sensor: temp_nspanel
    min_heating_off_time: ${min_off_time}s
    min_heating_run_time: ${min_run_time}s
    min_idle_time: ${min_idle_time}s
    visual:
      min_temperature: ${temp_min} ${temp_units}
      max_temperature: ${temp_max} ${temp_units}
      temperature_step: ${temp_step} ${temp_units}
    heat_action:
      - switch.turn_on: relay_${heater_relay}
    idle_action:
      - switch.turn_off: relay_${heater_relay}
    default_preset: "Off"
    on_boot_restore_from: memory
    preset:
      - name: "Off"
        default_target_temperature_low: ${temp_min} ${temp_units}
        mode: "off"
      - name: Home
        default_target_temperature_low: 21 ${temp_units}
    internal: false
    on_state:
      - logger.log: Climate state changed - Start
      - script.execute: addon_climate_update_page_climate
      - script.execute: addon_climate_update_page_home
      - logger.log: Climate state changed - End

packages:
  core_package: !include nspanel_esphome_addon_climate_base.yaml
