substitutions:
  device_name: nspanel
  nextion_update_url: ""

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: dev
    files:
      - nspanel_esphome.yaml # Core package
      - nspanel_esphome_advanced.yaml
    refresh: 300s

esphome:
  name_add_mac_suffix: true
  project:
    name: esphome.NSPanel_HA_Blueprint
    version: "4.1dev3"

dashboard_import:
  package_import_url: github://Blackymas/NSPanel_HA_Blueprint/nspanel_esphome_prebuilt.yaml@dev # Must be updated
  import_full_config: false

captive_portal:

button:
  - id: !extend tft_update
    internal: true

  - id: !extend tft_reparse_off
    internal: true
