---
substitutions:
  device_name: nspanel
  wifi_ssid: "nspanel"
  wifi_password: "NSPanel_HA_Blueprint"
  nextion_update_url: "https://github.com/Blackymas/NSPanel_HA_Blueprint/dummy"

packages:
  basic_package: !include ../nspanel_esphome.yaml  # Core package
  # advanced_package: !include ../esphome/nspanel_esphome_advanced.yaml
  # addon_climate_heat: !include ../esphome/nspanel_esphome_addon_climate_heat.yaml
  addon_climate_cool: !include ../esphome/nspanel_esphome_addon_climate_cool.yaml
  # addon_climate_dual: !include ../esphome/nspanel_esphome_addon_climate_dual.

bluetooth_proxy:
  id: ble_proxy

esp32_ble_tracker:
  id: ble_tracker

# Set Wi-Fi power save mode to "LIGHT" as required for Bluetooth on ESP32
wifi:
  power_save_mode: LIGHT

...
