---
name: Bug Report
description: If something isn't working as expected, let us know here.
title: "`Bug` "
labels: [Bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out a bug report!

        We aim to keep everything working perfectly, so your detailed reports are crucial.

        Report only one specific issue per submission. If you encounter another issue, create a new report for effective tracking and resolution.

        The more detail you provide, the quicker we can help.

        > [!WARNING]
        > Omit any private or sensitive information, as this bug report will be publicly visible.

  - type: markdown
    attributes:
      value: |
        ## Version Information
        Provide version numbers for TFT, ESPHome, and Blueprint. These can be found on your device's boot screen and in the automation where the blueprint is set.

  - type: input
    attributes:
      label: TFT Version
      description: Enter the TFT version number.
      placeholder: e.g., 4.1.4
    validations:
      required: false

  - type: input
    attributes:
      label: ESPHome Version
      description: Enter the ESPHome version number.
      placeholder: e.g., 4.1.4
    validations:
      required: false

  - type: input
    attributes:
      label: Blueprint Version
      description: Enter the Blueprint version number.
      placeholder: e.g., 4.1.4
    validations:
      required: false

  - type: dropdown
    attributes:
      label: Panel Model
      description: Select your NSPanel model.
      options:
        - NSPanel EU Model
        - NSPanel US Model
        - NSPanel US Model (Landscape)
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Bug Details

  - type: input
    attributes:
      label: What is the bug?
      description: Describe the bug clearly and concisely.
      placeholder: e.g., When I try this, I get this result, but I expected that...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Detail the steps to reproduce the behavior. Include screenshots or other relevant information.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error on '...'
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Additional Information (Optional)

  - type: textarea
    attributes:
      label: Your Panel's YAML
      description: Provide your panel's YAML configuration.
      render: yaml
      placeholder: |
        # Example YAML configuration
        # ...

  - type: textarea
    attributes:
      label: ESPHome logs
      description: Access these logs via the **Logs** button for your device on the ESPHome Dashboard.
      render: logs
    validations:
      required: false

  - type: textarea
    attributes:
      label: Home Assistant logs
      description: Access these logs from **Settings** > **System** > [**Logs**](https://my.home-assistant.io/redirect/logs/) in Home Assistant.
      render: logs
    validations:
      required: false
...
