---
name: Update Stable Tag

on:
  release:
    types: [published]

jobs:
  update-tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.0

    - name: Move and push tag
      run: |
        git tag -f stable ${{ github.event.release.tag_name }}
        git push -f origin stable
...
