---
name: Validate C++ (Clang Format)

# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - '**/*.h'
      - '**/*.c'
      - '**/*.cpp'
  pull_request:
    paths:
        - '**/*.h'
        - '**/*.c'
        - '**/*.cpp'
  workflow_dispatch:

jobs:
  clang-format-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: RafikFarhad/clang-format-github-action@v3
        with:
          sources: "esphome/components/nspanel_ha_blueprint/*.h,esphome/components/nspanel_ha_blueprint/*.c,esphome/components/nspanel_ha_blueprint/*.cpp"
...
