name: Validate Markdown

on:
  pull_request:
  push:
  workflow_dispatch:
      
jobs:
  markdown-check:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4.1.0

    # https://github.com/actionshub/markdownlint
    - name: Markdown Lint
      uses: actionshub/markdownlint@main

    # https://github.com/gaurav-nelson/github-action-markdown-link-check  
    - name: Markdown links
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        check-modified-files-only: 'yes'
