name: Validate YAML

on:
  push:
  pull_request:
  #schedule:
  #  - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  code_scan:
    name: Validate Blueprint YAML
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4.1.0
      - name: Validate YAML
        run: yamllint -c "./.rules/yamllint.yml"
