name: Validate ESPHome YAML

on:
  push:
    paths:
      - "nspanel_esphome_*.yaml"
  pull_request:
  #schedule:
  #  - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  code_scan:
    name: Validate ESPHome YAML
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4.1.0
      - name: Validate nspanel_esphome.yaml
        run: yamllint -c "./.yamllint/rules.yml" nspanel_esphome.yaml
      - name: Validate nspanel_esphome_advanced.yaml
        run: yamllint -c "./.yamllint/rules.yml" nspanel_esphome_advanced.yaml
      - name: Validate nspanel_esphome_addon_climate_cool.yaml
        run: yamllint -c "./.yamllint/rules.yml" nspanel_esphome_addon_climate_cool.yaml
      - name: Validate nspanel_esphome_addon_climate_heat.yaml
        run: yamllint -c "./.yamllint/rules.yml" nspanel_esphome_addon_climate_heat.yaml
      - name: Build core
        uses: esphome/build-action@v1.8.0
        with:
          yaml_file: "./.test/esphome_core.yaml"
      - name: Build core+advanced
        uses: esphome/build-action@v1.8.0
        with:
          yaml_file: "./.test/esphome_advanced.yaml"
