name: Validate Markdown

on:
  pull_request:
  push:
  workflow_dispatch:
      
jobs:
  markdown-check:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4.1.0

    # https://github.com/marketplace/actions/markdownlint-cli2-action
    - name: Identify changed files
      uses: tj-actions/changed-files@v41
      id: changed-files
      with:
        files: '**/*.md'
        separator: ","
    - name: Markdown Lint
      uses: DavidAnson/markdownlint-cli2-action@v14
      if: steps.changed-files.outputs.any_changed == 'true'
      with:
        globs: ${{ steps.changed-files.outputs.all_changed_files }}
        separator: ","
        config: '.rules/custom.markdownlint.jsonc'

    # https://github.com/gaurav-nelson/github-action-markdown-link-check  
    - name: Markdown links
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        check-modified-files-only: 'yes'

