name: Validate YAML

on:
  push:
  pull_request:
  #schedule:
  #  - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  code_scan:
    name: Validate YAML
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out code
        uses: actions/checkout@v4.1.0

      - name: Identify changed files
        uses: tj-actions/changed-files@v41
        id: changed-files
        with:
          files: '**/*.y*ml'
          separator: ","

      - name: Validate YAML
        if: steps.changed-files.outputs.any_changed == 'true'
        run: yamllint -c "./.rules/yamllint.yml" --list-files -f github -s "${{ steps.changed-files.outputs.all_changed_files }}"
